host: localhost
port: 30505

# The reset key will expire after x amount of time (12H) 
timeResetKey: 12

swagger:
  resourcePackage: com.dinenowinc.dinenow.resources

server:
  rootPath: '/api/v1/*'

jwtTokenSecret: e6a88cad578566a6348ffb8d1bf026

isInitDb: true
# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  # Logger-specific levels.
  loggers:
    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: INFO
    org.hibernate.SQL: INFO
    com.github.toastshaman: INFO

