'use strict';

export const NETWORK_ERROR_RECEIVED = 'NETWORK_ERROR_RECEIVED';
export const NETWORK_ERROR_CLEAR = 'NETWORK_ERROR_CLEAR';

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_START_SIGN_IN = 'AUTH_START_SIGN_IN';
export const AUTH_END_SIGN_IN = 'AUTH_END_SIGN_IN';
export const AUTH_SIGN_IN_ERROR = 'AUTH_SIGN_IN_ERROR';
export const AUTH_SIGN_IN_ERROR_RESET = 'AUTH_SIGN_IN_ERROR_RESET';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';

export const SEARCH_START = "SEARCH_START";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_RESULT_SET = "SEARCH_RESULT_SET";
export const SEARCH_RESULT_RESET = "SEARCH_RESULT_RESET";

export const RESTAURANT_DETAILS_REQUEST = "RESTAURANT_DETAILS_REQUEST";
export const RESTAURANT_DETAILS_SUCCESS = "RESTAURANT_DETAILS_SUCCESS";
export const RESTAURANT_DETAILS_RESULT_SET = "RESTAURANT_DETAILS_RESULT_SET";
export const RESTAURANT_DETAILS_RESULT_RESET = "RESTAURANT_DETAILS_RESULT_RESET";